
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdybaosdbikhgzehurdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkeWJhb3NkYmlraGd6ZWh1cmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MDQxNDUsImV4cCI6MjA1NjM4MDE0NX0.uNnEWjkmclXpHGaYq3wAmmVdSpi80zIpM0WJVGzC_OY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
